# 数学25-中考备考
# token: e2e=55B2D1619F0C8CF273169F8F1CA49A93; e2mf=79921c4a53e34001ba1dc78d7c03e188; token=79921c4a53e34001ba1dc78d7c03e188
# start_page: 384
# end_page: 620
# output_dir: "output"
# concurrency: 3
# delay_ms: 100
# catalogue_base_url: "https://zujuan.xkw.com/czsx/shijuan/bk/y2025p"


# 物理25-中考备考(已完成)
token: e2e=55B2D1619F0C8CF273169F8F1CA49A93; e2mf=79921c4a53e34001ba1dc78d7c03e188; token=79921c4a53e34001ba1dc78d7c03e188
start_page: 300
end_page: 338 #338 end
output_dir: "output"
concurrency: 3
delay_ms: 100
catalogue_base_url: "https://zujuan.xkw.com/czwl/shijuan/bk/y2025p"



#化学25-中考备考(已完成)
# token: e2e=55B2D1619F0C8CF273169F8F1CA49A93; e2mf=79921c4a53e34001ba1dc78d7c03e188; token=79921c4a53e34001ba1dc78d7c03e188
# start_page: 348
# end_page: 400
# output_dir: "output"
# concurrency: 3
# delay_ms: 100
# catalogue_base_url: "https://zujuan.xkw.com/czhx/shijuan/bk/y2025p"


#化学24-中考备考(已完成)
# token: e2e=55B2D1619F0C8CF273169F8F1CA49A93; e2mf=79921c4a53e34001ba1dc78d7c03e188; token=79921c4a53e34001ba1dc78d7c03e188
# start_page: 322
# end_page: 392
# output_dir: "output"
# delay_ms: 100
# catalogue_base_url: "https://zujuan.xkw.com/czhx/shijuan/bk/y2024p"



